crud_django/apps/album/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from .views import *

urlpatterns = patterns('',
    url(r'^$',  Album_Todos.as_view() , name='album_todos'),
    url(r'^album/nuevo/$', Album_Nuevo.as_view(), name='album_nuevo'),
    url(r'^album/(?P<pk>\d+)/$', Album_Detalle.as_view(), name='album_detalle'),
    url(r'^album/editar/(?P<pk>\d+)/$', Album_Modificar.as_view(), name='album_modificar'),
  	url(r'^album/eliminar/(?P<pk>\d+)/$', Album_Eliminar.as_view(), name='album_eliminar'),
  	url(r'^album/filtro/(?P<estilo_id>[\w_-]+)/', Album_Estilo.as_view(), name='album_estilo'),
)

crud_django/apps/musico/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from .views import *

urlpatterns = patterns('',
    url(r'^musicos/$',  Musico_Todos.as_view() , name='musicos'),
    url(r'^nuevo/$',  Musico_Nuevo.as_view() , name='musico_nuevo'),
    url(r'^(?P<pk>\d+)/$',  Musico_Detalle.as_view() , name='musico_detalle'),
    url(r'^editar/(?P<pk>\d+)/$', Musico_Modificar.as_view(), name='musico_modificar'),
  	url(r'^eliminar/(?P<pk>\d+)/$', Musico_Eliminar.as_view(), name='musico_eliminar'),
)

crud_django/crud_django/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crud_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^musico/', include('apps.musico.urls')),
    url(r'^', include('apps.album.urls')),
)

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT,}),
)

crud_django/apps/album/models.py
from django.db import models
from django.core.urlresolvers import reverse

from apps.musico.models import Musico
from apps.album import image

# Create your models here.
import datetime

YEAR_CHOICES = []
for r in range(1950, (datetime.datetime.now().year+1)):
    YEAR_CHOICES.append((r,r))

class Album(models.Model):

	def img_path(self,filename):
		ruta = 'discos/%s' % (str(filename))
		return ruta

	musico = models.ForeignKey(Musico)
	titulo = models.CharField(max_length=50)
	year = models.IntegerField(max_length=4 , choices=YEAR_CHOICES)
	portada = models.ImageField(upload_to=img_path)

	def __unicode__(self):
		return "%s" % self.titulo

	def get_absolute_url(self):
		return reverse('album_detalle', kwargs={'pk': self.pk})

	class Meta:
		ordering = ["musico"]

	def save(self, *args, **kwargs):
		super(Album, self).save(*args, **kwargs)
		self.titulo = self.titulo.capitalize()
		if not self.id and not self.portada: return

		image.resize(image.THUMB, self.portada)
		image.resize(image.SINGLE, self.portada)
		image.resize(image.HOME, self.portada)

	# los diferentes imagenes para el sitio
	def get_home_image_url(self):
		return image.get_url_by(image.HOME, self.portada)

	def get_thumb_image_url(self):
		return image.get_url_by(image.THUMB, self.portada)

	def get_single_image_url(self):
		return image.get_url_by(image.SINGLE, self.portada)

class Cancion(models.Model):
	titulo = models.CharField(max_length=50)
	album = models.ForeignKey(Album)

	def __unicode__(self):
		return self.titulo

crud_django/apps/musico/models.py
from django.db import models

from apps.album import image

# Create your models here.
ESTILOS = (
    ('blues', ('Blues')),
    ('jazz', ('Jazz')),
    ('rock', ('Rock')),
    ('clasica', ('Clasica')),
    ('tango', ('Tango')),
)

class Musico(models.Model):

	def img_path(self,filename):
		ruta = 'musicos/%s' % (str(filename))
		return ruta

	nombre = models.CharField(max_length=50)
	estilo = models.CharField(max_length=10, choices=ESTILOS)
	foto_perfil = models.ImageField(upload_to=img_path , null=True , blank=True)

	def __unicode__(self):
		return self.nombre

	def save(self, *args, **kwargs):
		super(Musico, self).save(*args, **kwargs)
		self.nombre = self.nombre.capitalize()
		if not self.id and not self.foto_perfil: return

		image.resize(image.THUMB, self.foto_perfil)
		image.resize(image.SINGLE, self.foto_perfil)
		image.resize(image.HOME, self.foto_perfil)

	# los diferentes imagenes para el sitio
	def get_home_image_url(self):
		return image.get_url_by(image.HOME, self.foto_perfil)

	def get_thumb_image_url(self):
		return image.get_url_by(image.THUMB, self.foto_perfil)

	def get_single_image_url(self):
		return image.get_url_by(image.SINGLE, self.foto_perfil)

crud_django/apps/album/views.py
from django.views.generic.base import TemplateView
from django.views.generic import CreateView, UpdateView, DetailView , ListView , DeleteView
from django.core.urlresolvers import reverse_lazy

from .models import Album
from .forms import AlbumForm

class Album_Todos(ListView):
	model = Album
	template_name = 'album/all_album.html'
	context_object_name = "all_album"

class Album_Detalle(DetailView):
    model = Album
    template_name = 'album/album.html'
    context_object_name = "album"

class Album_Nuevo(CreateView):
    model = Album
    success_url = reverse_lazy('album_todos')
    template_name = 'album/add_album.html'

class Album_Modificar(UpdateView):
    model = Album
    success_url = reverse_lazy('album_todos')
    template_name = 'album/add_album.html'

class Album_Eliminar(DeleteView):
    model = Album
    success_url = reverse_lazy('album_todos')
    template_name = 'album/eliminar_album.html'

class Album_Estilo(ListView):
    model = Album
    template_name = 'album/album_filtro.html'
    context_object_name = "all_album"

    def get_queryset(self):
        return Album.objects.filter(musico__estilo=self.kwargs['estilo_id']).order_by('musico__estilo')

crud_django/apps/musico/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DetailView , ListView , DeleteView
from django.core.urlresolvers import reverse_lazy

from .models import Musico
from apps.album.models import Album
# Create your views here.

class Musico_Todos(ListView):
	model = Musico
	template_name = 'musico/all_musico.html'
	context_object_name = "all_musico"

class Musico_Nuevo(CreateView):
	model = Musico
	template_name = 'musico/nuevo_musico.html'
	success_url = reverse_lazy('musicos')

class Musico_Detalle(DetailView):
    model = Musico
    template_name = 'musico/musico.html'
    context_object_name = "musico"

    def get_context_data(self, **kwargs):
		context = super(Musico_Detalle, self).get_context_data(**kwargs)
		musico = self.get_object()
		context['all_album'] = Album.objects.filter(musico=musico).order_by('titulo')
		return context

class Musico_Modificar(UpdateView):
    model = Musico
    success_url = reverse_lazy('musicos')
    template_name = 'musico/nuevo_musico.html'

class Musico_Eliminar(DeleteView):
    model = Musico
    success_url = reverse_lazy('musicos')
    template_name = 'musico/eliminar_musico.html'

crud_django/apps/album/templates/album/add_album.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		<article class="form">
		<form method="POST" enctype="multipart/form-data" autocomplete="off">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit"><span class="icon-check"></span> Guardar </button>
		</form>
		</article>
	</section>
{% endblock %}

crud_django/apps/album/templates/album/album.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		<article class="detalle">
			<figure>
				<img src="{{album.get_thumb_image_url}}"/>
			</figure>
			<h2><a href="{% url 'musico_detalle' album.musico.pk%}"><span class="icon-user"></span> {{album.musico.nombre}}</a></h2>
			<h2><span class="icon-music"></span> {{album.titulo}}</h2>
			<h3><span class="icon-tag"></span> {{album.musico.get_estilo_display}}</h3>
			<h3><span class="icon-calendar"></span> {{album.year}}</h3>
			<div class="crud">
				<a href="{% url 'album_modificar' album.id %}"><span class="icon-rotate-right"></span></a>
				<a href="{% url 'album_eliminar' album.id %}"><span class="icon-trash-o"></span></a>
			</div>
		</article>
	</section>
{% endblock %}

crud_django/apps/album/templates/album/album_filtro.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		{% for album in all_album %}
			<article>
				<figure>
					<a href="{% url 'album_detalle' album.pk %}"><img src="{{album.get_thumb_image_url}}"/></a>
				</figure>
				<h2>
					<a href="{% url 'musico_detalle' album.musico.pk %}">
						<span class="icon-user"></span> {{album.musico.nombre}}
					</a>
				</h2>
				<h2>
					<a href="{% url 'album_detalle' album.pk %}">
						<span class="icon-music"></span> {{album.titulo}}
					</a>
				</h2>
				<h3>
					<span class="icon-tag"></span> {{album.musico.get_estilo_display}}
				</h3>
			</article>
		{% empty %}
			<div class="empty">
				<label> No Hay Discos </label>
				<span class="icon-book"></span>
			</div>
		{% endfor %}
	</section>
{% endblock %}

crud_django/apps/album/templates/album/all_album.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		{% for album in all_album %}
			<article>
				<figure>
					<a href="{% url 'album_detalle' album.pk %}"><img src="{{album.get_thumb_image_url}}"/></a>
				</figure>
				<h2>
					<a href="{% url 'musico_detalle' album.musico.pk %}">
						<span class="icon-user"></span> {{album.musico.nombre}}
					</a>
				</h2>
				<h2>
					<a href="{% url 'album_detalle' album.pk %}">
						<span class="icon-music"></span> {{album.titulo}}
					</a>
				</h2>
				<h3>
					<a href="{% url 'album_estilo' album.musico.estilo %}">
						<span class="icon-tag"></span> {{album.musico.get_estilo_display}}
					</a>
				</h3>
			</article>
		{% empty %}
			<div class="empty">
				<label> No Hay Discos </label>
				<span class="icon-book"></span>
			</div>
		{% endfor %}
	</section>
{% endblock %}

crud_django/apps/album/templates/album/eliminar_album.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		<article class="form">
		<form method="POST" enctype="multipart/form-data" autocomplete="off">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit"><span class="icon-check"></span> Eliminar </button>
		</form>
		</article>
	</section>
{% endblock %}

crud_django/apps/album/templates/base_app.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> LiveMusic </title>
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="{% static "icomoon/style.css" %}">
</head>
<body>
	<header>
		<div class="logo">
			<a href="https://github.com/CristhGunners/"><span class="icon-github-alt"></span></a>
			<a href="https://twitter.com/CristhGunners"><span class="icon-twitter"></span></a>
		</div>
		<h1><a href="/"> Live Music </a></h1>
		<div id="add">
			<a href="{% url 'musico_nuevo' %}"><span class="icon-user-add"></span></a>
			<a href="{% url 'album_nuevo' %}"><span class="icon-feather"></span></a>
			<a href="{% url 'musicos' %}"><span class="icon-group"></span></a>
		</div>
	</header>
	<section>
		{% block content %}{% endblock %}
	</section>
	<!--<footer>
		<h2> LiveMusic </h3>
		<h3><a href="#"><span class="icon-twitter"></span> @CristhGunners </h2></a>
	</footer>-->
</body>
</html>

crud_django/apps/musico/templates/musico/all_musico.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		{% for musico in all_musico %}
			<article>
				<figure>
					<a href="{% url 'musico_detalle' musico.pk %}"><img src="{{musico.get_thumb_image_url}}"/></a>
				</figure>
				<h2>
					<a href="{% url 'musico_detalle' musico.pk %}">
						<span class="icon-user"></span> {{musico.nombre}}
					</a>
					</h2>
				<h3><span class="icon-tag"></span> {{musico.get_estilo_display}}</h3>
			</article>
		{% empty %}
			<div>
				<label> No Hay Musicos </label>
				<span class="icon-book"></span>
			</div>
		{% endfor %}
	</section>
{% endblock %}

crud_django/apps/musico/templates/musico/eliminar_musico.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		<article class="form">
		<form method="POST" enctype="multipart/form-data" autocomplete="off">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit"><span class="icon-check"></span> Eliminar </button>
		</form>
		</article>
	</section>
{% endblock %}

crud_django/apps/musico/templates/musico/musico.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		<article class="detalle musico">
			<figure>
				<img src="{{musico.get_thumb_image_url}}"/>
			</figure>
			<h2><span class="icon-user"></span> {{musico.nombre}}</h2>
			<h3><span class="icon-tag"></span> {{musico.get_estilo_display}}</h3>
			<div class="crud">
				<a href="{% url 'musico_modificar' musico.pk %}"><span class="icon-rotate-right"></span></a>
				<a href="{% url 'musico_eliminar' musico.pk %}"><span class="icon-trash-o"></span></a>
			</div>
		</article>
		{% for album in all_album %}
			<article>
				<figure>
					<a href="{% url 'album_detalle' album.pk %}"><img src="{{album.get_thumb_image_url}}"/></a>
				</figure>
				<h2>
					<a href="{% url 'musico_detalle' album.musico.pk %}">
						<span class="icon-user"></span> {{album.musico.nombre}}
					</a>
				</h2>
				<h2>
					<a href="{% url 'album_detalle' album.pk %}">
						<span class="icon-music"></span> {{album.titulo}}
					</a>
				</h2>
				<h3><span class="icon-tag"></span> {{album.musico.get_estilo_display}}</h3>
			</article>
		{% empty %}
			<div class="empty">
				<label> No Hay Discos </label>
				<span class="icon-folder"></span>
			</div>
		{% endfor %}
	</section>
{% endblock %}

crud_django/apps/musico/templates/musico/nuevo_musico.html
{% extends 'base_app.html '%}

{% block content %}
	<section id="all-album">
		<article class="form">
		<form method="POST" enctype="multipart/form-data" autocomplete="off">
			{% csrf_token %}
			{{form.as_p}}
			<button type="submit"><span class="icon-check"></span> Guardar </button>
		</form>
		</article>
	</section>
{% endblock %}